package com.quickcart.backend.dto;

/**
 * Standardized error codes for the application.
 * Used to provide consistent error identification across the API.
 */
public enum ErrorCode {
    ORDER_ALREADY_PAID("ORDER_ALREADY_PAID"),
    ORDER_ALREADY_CANCELLED("ORDER_ALREADY_CANCELLED"),
    INVALID_ORDER_STATUS("INVALID_ORDER_STATUS"),
    INVALID_STATE_TRANSITION("INVALID_STATE_TRANSITION"),
    INVALID_PAYMENT_SIGNATURE("INVALID_PAYMENT_SIGNATURE"),
    ORDER_ACCESS_DENIED("ORDER_ACCESS_DENIED"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
    EMAIL_ALREADY_EXISTS("EMAIL_ALREADY_EXISTS"),
    INSUFFICIENT_STOCK("INSUFFICIENT_STOCK"),
    OUT_OF_STOCK("OUT_OF_STOCK"),
    PAYMENT_ALREADY_PROCESSED("PAYMENT_ALREADY_PROCESSED"),
    ORDER_EXPIRED("ORDER_EXPIRED"),
    DUPLICATE_REQUEST("DUPLICATE_REQUEST"),
    WEBHOOK_ERROR("WEBHOOK_ERROR"),
    INVALID_ROLE("INVALID_ROLE"),
    VALIDATION_FAILED("VALIDATION_FAILED"),
    BAD_REQUEST("BAD_REQUEST"),
    UNAUTHORIZED("UNAUTHORIZED"),
    FORBIDDEN("FORBIDDEN"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
